class_name Cosmetics
extends RefCounted
## Character-customization catalog + rules (Phase 2 suite, Track 2).
## Data lives in res://assets/customize/catalog.json (generated by
## tools/gen_cosmetics.py alongside the art). Everything here is
## cosmetic-only: no stats, no power, zero gameplay effect.

const CATALOG_PATH := "res://assets/customize/catalog.json"
const ART_DIR := "res://assets/art/customize/%s/%s.png"

const RARITY_COLORS := {
	"Street": Color(0.62, 0.63, 0.66),
	"Rare": Color(0.35, 0.65, 1.0),
	"Epic": Color(0.72, 0.42, 1.0),
	"Legendary": Color(1.0, 0.78, 0.25),
}

static var _cat: Dictionary = {}


static func catalog() -> Dictionary:
	if _cat.is_empty():
		if ResourceLoader.exists(CATALOG_PATH):
			_cat = JSON.parse_string(FileAccess.get_file_as_string(CATALOG_PATH))
		if _cat.is_empty():
			_cat = {"items": {}, "slots": [], "rarities": []}
	return _cat


static func items() -> Dictionary:
	return catalog().get("items", {})


static func slots() -> Array:
	return catalog().get("slots", ["headgear", "gloves", "kicks", "accessory", "facepaint", "eyes"])


static func get_item(item_id: String) -> Dictionary:
	return items().get(item_id, {})


## Overlay PNG paths for an item on a fighter art dir (e.g. "rook").
## Returns [{canvas, path}]; hoods ship a second torso canvas.
static func art_files(art_key: String, item_id: String) -> Array:
	var out := []
	var spec := get_item(item_id)
	if spec.is_empty():
		return out
	for canvas in spec.get("canvases", []):
		var fname := item_id
		if canvas != spec["canvases"][0]:
			fname = item_id + "_" + canvas
		var p := ART_DIR % [art_key, fname]
		if ResourceLoader.exists(p):
			out.append({"canvas": canvas, "path": p})
	return out


static func rarity_color(rarity: String) -> Color:
	return RARITY_COLORS.get(rarity, Color.WHITE)


## Season gate: returns the season id if the item is season-locked and the
## season is NOT currently active, else "".
static func season_gate(item: Dictionary) -> String:
	var u: Dictionary = item.get("unlock", {})
	if u.get("type") != "season":
		return ""
	var sid := str(u.get("season", ""))
	if sid == "takeover":
		return ""  # Season 1 (THE TAKEOVER) is the live season.
	if sid == "halloween" and Time.get_date_dict_from_system()["month"] == 10:
		return ""
	return sid


## "" = purchasable/unlocked, else a human lock reason.
static func lock_reason(save: SaveData, item_id: String) -> String:
	var item := get_item(item_id)
	if item.is_empty():
		return "Unknown item."
	if save.owned_cosmetics.get(item_id, false):
		return ""
	var u: Dictionary = item.get("unlock", {})
	var t := str(u.get("type", "shop"))
	if t == "boss":
		var need := int(u.get("boss", 99))
		if save.bosses_beaten < need:
			return "Beat %d bosses (%d/%d)." % [need, save.bosses_beaten, need]
		return ""
	var sg := season_gate(item)
	if sg != "":
		return "Season reward — returns with %s." % sg.capitalize()
	return ""


## Daily shop rotation (deterministic per date): Street items always stocked;
## 3 Rare + 2 Epic shop items rotate. Season/boss items never in the shop.
static func shop_stock(save: SaveData) -> Array:
	var today := Time.get_date_dict_from_system()
	var key := "%04d-%02d-%02d" % [today["year"], today["month"], today["day"]]
	if str(save.cosmetic_stock.get("date", "")) == key:
		return save.cosmetic_stock.get("ids", [])
	var street := []
	var rare := []
	var epic := []
	for item_id in items().keys():
		var item: Dictionary = items()[item_id]
		var u: Dictionary = item.get("unlock", {})
		if u.get("type") != "shop":
			continue
		match str(item.get("rarity", "Street")):
			"Street":
				street.append(item_id)
			"Rare":
				rare.append(item_id)
			"Epic":
				epic.append(item_id)
	var rng := RandomNumberGenerator.new()
	rng.seed = hash(key)
	_seeded_shuffle(rare, rng)
	_seeded_shuffle(epic, rng)
	var ids: Array = street + rare.slice(0, 3) + epic.slice(0, 2)
	save.cosmetic_stock = {"date": key, "ids": ids}
	save.save_game()
	return ids


static func _seeded_shuffle(a: Array, rng: RandomNumberGenerator) -> void:
	for i in range(a.size() - 1, 0, -1):
		var j := rng.randi_range(0, i)
		var t = a[i]
		a[i] = a[j]
		a[j] = t
